import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { renderToStaticMarkup } from "react-dom/server";
import { MarketingHome } from "./components/MarketingHome";

describe("MarketingHome", () => {
  test("introduces nudge as the public marketing site with a path into the app", () => {
    const html = renderToStaticMarkup(<MarketingHome />);

    expect(html).toContain("nudge");
    expect(html).toContain("Sticky-note capture. AI follow-through.");
    expect(html).toContain(">nudge</span>");
    expect(html).not.toContain("marketing-nudge-word-label");
    expect(html).toContain("turns sticky notes into next steps.");
    expect(html).toContain("Capture rough thoughts fast.");
    expect(html).toContain("reminders, drafts, tasks, and follow-ups");
    expect(html).toContain("approve or edit");
    expect(html).toContain("sticky note -&gt; reminder");
    expect(html).toContain("loose thought -&gt; task");
    expect(html).toContain("nothing sends without approval");
    expect(html).toContain("Open nudge");
    expect(html).toContain("try nudge");
    expect(html).toContain("see note -&gt; action");
    expect(html).toContain('data-slot="marketing-cta-reassurance"');
    expect(html).toContain("Drop the note now. Decide what moves later.");
    expect(html).toContain('alt="nudge"');
    expect(html).toContain('aria-label="Example note transformed into next actions"');
    expect(html).toContain("FAQ");
    expect(html).toContain('href="/faq"');
    expect(html).toContain('data-slot="marketing-note-action-flow"');
    expect(html).toContain('data-slot="marketing-sticky-note"');
    expect(html).toContain('data-slot="marketing-action-queue"');
    expect(html).toContain("follow up with Sam about launch date");
    expect(html).toContain("ask if invoice is blocked");
    expect(html).toContain("remind me friday");
    expect(html).toContain("draft reply");
    expect(html).toContain("create reminder");
    expect(html).toContain("schedule follow-up");
    expect(html).toContain("approve");
    expect(html).toContain("edit");
    expect(html).toContain("skip");
    expect(html).toContain('data-slot="marketing-brand"');
    expect(html).toContain('data-slot="marketing-action"');
    expect(html).toContain('data-slot="marketing-headline"');
    expect(html).toContain('data-slot="marketing-header-cluster"');
    expect(html).toContain("justify-center");
    expect(html).toContain('data-slot="marketing-nudge-word"');
    expect(html).not.toContain('data-slot="marketing-nudge-word-bleed"');
    expect(html).toContain('data-slot="marketing-hero-artwork"');
    expect(html).not.toContain("metaball");
    expect(html).not.toContain("paper-shader-mount");
    expect(html).toContain('data-slot="marketing-hero-halftone-dots"');
    expect(html).toContain('data-hero-image="/images/nudge-hero-open-sky.png"');
    expect(html).toContain('data-halftone-treatment="visible-hero-dots"');
    expect(html).toContain('aria-hidden="true"');
    expect(html).toContain('data-slot="marketing-proof-grid"');
    expect(html).toContain('href="https://app.explorenudge.com"');
    expect(html).not.toContain("Read FAQ");
    expect(html).not.toContain("tracking-[");
    expect(html).not.toContain("font-[790]");
    expect(html).not.toContain("lava-map");
    expect(html).not.toContain("Daily operating loop");
    expect(html).not.toContain("Capture, clarify, return");
    expect(html).not.toContain("Capture · Clarify · Return");
    expect(html).not.toContain("One place to keep");
    expect(html).not.toContain("Personal AI teammate");
    expect(html).not.toContain("source-linked proposals");
    expect(html).not.toContain("Proposals wait for review");
    expect(html).not.toContain("Human-in-the-loop by design");
    expect(html).not.toContain("done work");
    expect(html).not.toContain("AI layer");
    expect(html).not.toContain("right direction");
    expect(html).not.toContain('data-slot="marketing-hero-image"');
    expect(html).not.toContain(">method<");
    expect(html).not.toContain(">Open app<");
    expect(html).not.toContain("See how it works");
    expect(html).not.toContain('id="faq"');
    expect(html).not.toContain('data-slot="marketing-faq-list"');
    expect(html).not.toContain(">Nudge<");
    expect(html).not.toContain("Open Nudge");
    expect(html).not.toContain("What does nudge keep track of?");
    expect(html).not.toContain("private by default");
  });

  test("uses the logo palette and Arista display font for a clean minimal nudge-specific marketing page", () => {
    const html = renderToStaticMarkup(<MarketingHome />);
    const logo = readFileSync(
      new URL("../public/icons/nudge-logo-lockup-blobby-n-transparent.svg", import.meta.url),
      "utf8",
    );
    const heroImage = readFileSync(
      new URL("../public/images/nudge-hero-open-sky.png", import.meta.url),
    );
    const aristaFont = readFileSync(
      new URL("../public/fonts/arista/Arista.ttf.woff", import.meta.url),
    );
    const css = readFileSync(new URL("./styles.css", import.meta.url), "utf8");

    expect(heroImage.subarray(0, 8).toString("hex")).toBe("89504e470d0a1a0a");
    expect(heroImage.readUInt32BE(16)).toBe(1821);
    expect(heroImage.readUInt32BE(20)).toBe(864);
    expect(aristaFont.subarray(0, 4).toString("ascii")).toBe("wOFF");
    expect(html).toContain('src="/icons/nudge-logo-lockup-blobby-n-transparent.svg"');
    expect(html).toContain('data-slot="marketing-brand-logo"');
    expect(html).not.toContain('data-slot="marketing-brand-dot"');
    expect(logo).toContain("nudge logo lockup");
    expect(logo).toContain("transparent background");
    expect(html).not.toContain("headline-overlay");
    expect(css).toContain("--logo-orange: #f14f23");
    expect(css).toContain("--logo-ink: #1a2735");
    expect(css).toContain("--page: #fffdf8");
    expect(css).toContain('@import "@fontsource-variable/geist";');
    expect(css).not.toContain('@import "@fontsource-variable/comfortaa";');
    expect(css).toContain("--font-sans:");
    expect(css).toContain('"Geist Variable", Geist');
    expect(css).toContain("--font-display:");
    expect(css).toContain('Arista, "Geist Variable"');
    expect(css).toContain("font-family: Arista");
    expect(css).toContain('url("/fonts/arista/Arista.ttf.woff") format("woff")');
    expect(css).not.toContain("Nudge Aristotelica");
    expect(css).not.toContain("Comfortaa Variable");
    expect(css).toContain("font-family: var(--font-sans)");
    expect(css).toContain("font-family: var(--font-display)");
    expect(css).toContain(".nudge-word");
    expect(css).toContain("font-weight: 400");
    expect(css).toContain("letter-spacing: 0");
    expect(css).not.toContain(".hero-title,\n  .brand-mark");
    expect(css).not.toContain('[data-slot="marketing-action"]');
    expect(css).not.toContain(".loop-node,");
    expect(html).toContain('data-slot="marketing-note-action-flow"');
    expect(html).toContain("grid-cols-[minmax(0,1fr)_minmax(18rem,28rem)]");
    expect(html).toContain("h-svh");
    expect(html).toContain("overflow-clip");
    expect(css).toContain("color: var(--logo-orange)");
    expect(css).toContain(".nudge-word");
    expect(css).toContain("transition-property: transform");
    expect(css).not.toContain("font-weight: 840");
    expect(css).not.toContain(".nudge-word__label");
    expect(css).not.toContain(".nudge-word__bleed");
    expect(css).not.toContain("nudge-word-bleed");
    expect(css).not.toContain("background-clip: text");
    expect(css).not.toContain("-webkit-text-fill-color: transparent");
    expect(css).toContain(".hero-artwork");
    expect(css).toContain("--hero-halftone-opacity: 1");
    expect(css).toContain("background: #f2f1e8");
    expect(css).toContain(".hero-artwork__halftone");
    expect(css).not.toContain(".hero-metaballs");
    expect(css).not.toContain(".hero-metaball-field");
    expect(css).toContain("opacity: var(--hero-halftone-opacity)");
    expect(css).toContain("z-index: 3");
    expect(css).toContain("mix-blend-mode: normal");
    expect(css).toContain("--hero-header-clearance-mask");
    expect(css).toContain("radial-gradient(");
    expect(css).toContain("ellipse 86% 15rem at 50% 0");
    expect(css).toContain("-webkit-mask-image: var(--hero-header-clearance-mask)");
    expect(css).toContain("mask-image: var(--hero-header-clearance-mask)");
    expect(css).toContain("mask-repeat: no-repeat");
    expect(html).toContain("hero-artwork__readability-wash");
    expect(html).toContain("ellipse 70% 8rem at 50% 100%");
    expect(css).not.toContain(".hero-artwork::before");
    expect(css).not.toContain(".hero-artwork::after");
    expect(css).not.toContain(".hero-artwork__image");
    expect(css).toContain('data-nudge-direction="right"');
    expect(css).toContain(".note-action-flow");
    expect(css).toContain(".sticky-note");
    expect(css).toContain(".action-card");
    expect(css).toContain("@media (prefers-reduced-motion: reduce)");
    expect(css).not.toContain("filter: blur");
    expect(css).not.toContain("signal-aura");
    expect(css).not.toContain("text-transform: lowercase");
    expect(css).not.toContain("top: 66%");
    expect(css).not.toContain("left: 83%");
    expect(css).not.toContain("transition: all");
    expect(html).toContain("text-[#9a3219]");
    expect(html).toContain("text-[rgba(26,39,53,0.82)]");
    expect(html).toContain("text-[rgba(26,39,53,0.74)]");
    expect(html).toContain("text-[rgba(26,39,53,0.72)]");
    expect(html).not.toContain('data-slot="marketing-nudge-word" type="button"');
  });

  test("keeps short mobile screens from clipping the hero content", () => {
    const html = renderToStaticMarkup(<MarketingHome />);

    expect(html).toContain('data-slot="marketing-hero-eyebrow"');
    expect(html).toContain("[@media(min-width:561px)_and_(max-width:760px)]:hidden");
    expect(html).toContain('data-slot="marketing-hero-stack"');
    expect(html).toContain("[@media(min-width:561px)_and_(max-width:760px)]:self-start");
    expect(html).toContain("[@media(min-width:561px)_and_(max-width:760px)]:pt-[1.3rem]");
    expect(html).toContain('data-slot="marketing-hero-actions"');
    expect(html).toContain('data-slot="marketing-action-proof-panel"');
    expect(html).toContain('data-slot="marketing-proof-strip"');
    expect(html).toContain("[@media(max-width:560px)_and_(max-height:720px)]:hidden");
    expect(html).toContain("[@media(max-width:560px)_and_(max-height:720px)]:pt-[0.3rem]");
    expect(html).toContain("[@media(max-width:560px)_and_(max-height:720px)]:text-[0.9rem]");
    expect(html).toContain("max-[360px]:basis-[8.55rem]");
  });

  test("keeps hero text readable over the halftone background", () => {
    const html = renderToStaticMarkup(<MarketingHome />);
    const css = readFileSync(new URL("./styles.css", import.meta.url), "utf8");

    expect(html).toContain('data-slot="marketing-hero-copy"');
    expect(html).toContain('data-copy="Capture rough thoughts fast.');
    expect(html).toContain("hero-copy");
    expect(html).toContain("hero-text-knockout");
    expect(html).toContain('data-slot="marketing-hero-eyebrow"');
    expect(html).toContain('data-slot="marketing-headline"');
    expect(html).toContain('data-slot="marketing-proof-label"');
    expect(html).toContain('data-copy="messy note in, useful action out"');
    expect(html).toContain("proof-label-knockout");
    expect(html).toContain('data-slot="marketing-proof-copy"');
    expect(html).toContain('class="hero-title text-logo-ink');
    expect(html).not.toContain("hero-title hero-text-knockout");
    expect(html).toContain('class="hero-text-knockout inline-block');
    expect(html).toContain("cta-reassurance hero-text-knockout");
    expect(html).toContain("action-card");
    expect(css).toContain(".hero-text-knockout");
    expect(css).toContain("0 0 0.9rem rgba(255, 253, 248, 0.82)");
    expect(css).toContain("0 0 1.45rem rgba(255, 253, 248, 0.62)");
    expect(css).toContain(".hero-copy::before");
    expect(css).toContain(".cta-reassurance::before");
    expect(css).toContain(".proof-label-knockout::before");
    expect(css).toContain("content: attr(data-copy)");
    expect(css).toContain("0 0 1.25rem rgba(255, 253, 248, 0.82)");
    expect(css).toContain("0 0 2rem rgba(255, 253, 248, 0.62)");
    expect(css).toContain("text-shadow:");
    expect(css).not.toContain("ellipse 96% 76% at 48% 52%");
  });
});
